package rules

import (
	"prushton.com/randochess/v2/board"
	rsf "prushton.com/randochess/v2/rules/rulesetFunctions"
)

var AllRulesets map[string]Ruleset = map[string]Ruleset{
	"Default": {
		Name: "Default",
		PieceRules: map[board.PieceType]func(board.Board, int, int) bool{
			board.Pawn:   rsf.DefaultPawn,
			board.Rook:   rsf.DefaultRook,
			board.Knight: rsf.DefaultKnight,
			board.Bishop: rsf.DefaultBishop,
			board.King:   rsf.DefaultKing,
			board.Queen:  rsf.DefaultQueen,
		},
		Width:     8,
		Height:    8,
		Move:      rsf.DefaultMove,
		GetWinner: rsf.DefaultGetWinner,
		InitBoard: rsf.DefaultInitBoard,
	},
	"Open World": {
		Name: "Open World",
		PieceRules: map[board.PieceType]func(board.Board, int, int) bool{
			board.Pawn:   rsf.DefaultPawn,
			board.Rook:   rsf.DefaultRook,
			board.Knight: rsf.DefaultKnight,
			board.Bishop: rsf.DefaultBishop,
			board.King:   rsf.DefaultKing,
			board.Queen:  rsf.DefaultQueen,
		},
		Width:     16,
		Height:    16,
		Move:      rsf.DefaultMove,
		GetWinner: rsf.DefaultGetWinner,
		InitBoard: rsf.DefaultInitBoard,
	},
	"Oops! All Knights!": {
		Name: "Oops! All Knights!",
		PieceRules: map[board.PieceType]func(board.Board, int, int) bool{
			board.Pawn:   rsf.DefaultKnight,
			board.Rook:   rsf.DefaultKnight,
			board.Knight: rsf.DefaultKnight,
			board.Bishop: rsf.DefaultKnight,
			board.King:   rsf.DefaultKnight,
			board.Queen:  rsf.DefaultKnight,
		},
		Width:     8,
		Height:    8,
		Move:      rsf.DefaultMove,
		GetWinner: rsf.DefaultGetWinner,
		InitBoard: rsf.DefaultInitBoard,
	},
	"PREPARE THYSELF": {
		Name: "PREPARE THYSELF",
		PieceRules: map[board.PieceType]func(board.Board, int, int) bool{
			board.Pawn:   rsf.PrepareThyselfPawn,
			board.Rook:   rsf.DefaultRook,
			board.Knight: rsf.DefaultKnight,
			board.Bishop: rsf.DefaultBishop,
			board.King:   rsf.DefaultKing,
			board.Queen:  rsf.DefaultQueen,
		},
		Width:     8,
		Height:    8,
		Move:      rsf.DefaultMove,
		GetWinner: rsf.DefaultGetWinner,
		InitBoard: rsf.DefaultInitBoard,
	},
	"Have a plan to kill everyone you meet": {
		Name: "Have a plan to kill everyone you meet",
		PieceRules: map[board.PieceType]func(board.Board, int, int) bool{
			board.Pawn:   rsf.DefaultPawn,
			board.Rook:   rsf.DefaultRook,
			board.Knight: rsf.DefaultKnight,
			board.Bishop: rsf.PlanBishop,
			board.King:   rsf.DefaultKing,
			board.Queen:  rsf.DefaultQueen,
		},
		Width:     8,
		Height:    8,
		Move:      rsf.DefaultMove,
		GetWinner: rsf.DefaultGetWinner,
		InitBoard: rsf.DefaultInitBoard,
	},
	"Atomic Chess": {
		Name: "Atomic Chess",
		PieceRules: map[board.PieceType]func(board.Board, int, int) bool{
			board.Pawn:   rsf.DefaultPawn,
			board.Rook:   rsf.DefaultRook,
			board.Knight: rsf.DefaultKnight,
			board.Bishop: rsf.DefaultBishop,
			board.King:   rsf.DefaultKing,
			board.Queen:  rsf.DefaultQueen,
		},
		Width:     8,
		Height:    8,
		Move:      rsf.AtomicChessMove,
		GetWinner: rsf.DefaultGetWinner,
		InitBoard: rsf.DefaultInitBoard,
	},
	"Knook": {
		Name: "Knook",
		PieceRules: map[board.PieceType]func(board.Board, int, int) bool{
			board.Pawn:   rsf.DefaultPawn,
			board.Rook:   rsf.Knook,
			board.Knight: rsf.DefaultKnight,
			board.Bishop: rsf.DefaultBishop,
			board.King:   rsf.DefaultKing,
			board.Queen:  rsf.DefaultQueen,
		},
		Width:     8,
		Height:    8,
		Move:      rsf.DefaultMove,
		GetWinner: rsf.DefaultGetWinner,
		InitBoard: rsf.DefaultInitBoard,
	},
	"Dementia": {
		Name: "Dementia",
		PieceRules: map[board.PieceType]func(board.Board, int, int) bool{
			board.Pawn:   rsf.DefaultPawn,
			board.Rook:   rsf.DefaultRook,
			board.Knight: rsf.DefaultKnight,
			board.Bishop: rsf.DefaultBishop,
			board.King:   rsf.DefaultKing,
			board.Queen:  rsf.DefaultQueen,
		},
		Width:     8,
		Height:    8,
		Move:      rsf.DementiaMove,
		GetWinner: rsf.DefaultGetWinner,
		InitBoard: rsf.DefaultInitBoard,
	},
	"Checkers": {
		Name: "Chechers",
		PieceRules: map[board.PieceType]func(board.Board, int, int) bool{
			board.Pawn:   rsf.DefaultPawn,
			board.Rook:   rsf.DefaultRook,
			board.Knight: rsf.DefaultKnight,
			board.Bishop: rsf.DefaultBishop,
			board.King:   rsf.DefaultKing,
			board.Queen:  rsf.DefaultQueen,
		},
		Width:     8,
		Height:    8,
		Move:      rsf.CheckersMove,
		GetWinner: rsf.CheckersGetWinner,
		InitBoard: rsf.CheckersInitBoard,
	},
}
